a = int(input('整数A:'))
b = int(input('整数B:'))

print('a + b = {}'.format(a+b))
print('a - b = {}'.format(a-b))
print('a * b = {}'.format(a*b))
print('a / b = {}'.format(a/b))
print('a // b = {}'.format(a//b))
print('a % b = {}'.format(a%b))
print('a ** b = {}'.format(a**b))
